### ISSUE TITLE
invalid inputs test cases are not covered.. 

### ISSUE THREAD

**Issue by adityagampa** [rahul-msRnD/code-a-day#1]
![saiyana-1](https://cloud.githubusercontent.com/assets/10786261/12825100/9e726e24-cb9a-11e5-9cfc-f2cd7b90de8c.png)
@saiyana 
Also check for leap years.. :)

**Comment by saiyana** [comment]
Leap years condition is already checked in the first if in "noOfDays" function :/ (BEcause only feb causes a change)
And i made some changes for invalid input cases.. :)

**Comment by rahul-msRnD** [comment]
@saiyana  **leap years** are not completely checked in the noOfDays function. You missed a case in **leap year theory**. Have a look at it. :)

**Comment by saiyana** [comment]
Updated :) Thanks!

**Comment by adityagampa** [comment]
**Another issue.. :P  1<2<3 is not allowed in c i guess.. this prints 'h' .. where as it shuld print 'e'..**
![saiyana-1-1](https://cloud.githubusercontent.com/assets/10786261/12867910/58a3f44e-cd20-11e5-9a09-f3677a3e87b3.png)

*_check ur code once for 31-08-2015 and 30-08-2015 .. it should return 2.. *_

![saiyana-1-3](https://cloud.githubusercontent.com/assets/10786261/12867911/58b37be4-cd20-11e5-87a5-cbb5ab2c1032.png)

@saiyana

**Comment by saiyana** [comment]
Ya that is not valid. I changed it :)
